x-app: &app
  env_file:
    - ./.env
  restart: always

x-default-logging: &default-logging
  options:
    max-size: '10m'
    max-file: '3'
  driver: json-file

services:
  source-db:
    image: postgres:16
    container_name: etl_coro_db
    <<: *app
    logging: *default-logging
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      TZ: "Europe/Moscow"
      PGTZ: "Europe/Moscow"
    volumes:
      - source_db_data:/var/lib/postgresql/data/
      - ./init_scripts/init_source_db.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  source_db_data: